##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
XSERVER="xserver-xorg xinit xinput xserver-xorg-utils xf86-input-evdev xf86-input-libinput xf86-video-fbdev" 
#CAGE="cage seatd xwayland" 
PYGOBJECT="gobject-introspection-dev gcc cairo-dev pkgconfig python3-dev gtk+3-dev" 
MISC="librsvg openjpeg dbus-glib-dev autoconf python3-venv" 
OPTIONAL="mpv-dev" 
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
      echo_ok "XServer" 
      #echo_text "Wayland is EXPERIMENTAL, needs kms/drm drivers, and doesn't support DPMS" 
##edit-out##
      #echo "Press enter for default (Xserver)" 
      read -r -e -p "Press enter for XServer" 
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
##edit-out##
